# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

#Declare the orbs necessary to run your YAML script (these are like pre-packaged code)
orbs:
  #These are the two available orbs for SFDX, top is to run SFDX commands, bottomr to run Apex Tests
  salesforce-sfdx: circleci/salesforce-sfdx@2.1.0
  salesforce-apex: circleci/salesforce-apex@1.0.1

# This is where we define the individul jobs
jobs:
  #This is the name of our job (this can be named anything)
  setup_scratch_org:
    #Salesforce utilizes the latest node docker image
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Building org"
  #This is the name of our job (this can be named anything)    
  run_apex_tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Running tests"

#Workflows determine the order in which your individual jobs run      
workflows:
  version: 2.1

  #This is the name of the workflow (this can be named anything)    
  setup_scratch_org_and_run_apex_test:
    #This is the order that we are executing our jobs (use the job names from above)
    jobs:
      - setup-scratch-org
      - run-apex-tests